# frozen_string_literal: true

source 'https://rubygems.org'

# Use the local laneful-ruby gem
gem 'laneful-ruby', path: '../'

# Additional gems for examples
gem 'sinatra', '~> 3.0'
gem 'json', '~> 2.6'